sudo: false
language: node_js
node_js: 14
install:
    - npm install
before_script:
    - npm run build
script:
    - npm run test
    - chmod 755 ./deploy.sh
    - ./deploy.sh
after_success:
    - npm run coverall
